### ISSUE TITLE
HTML links are not correctly displayed as hyperlinks

### ISSUE THREAD

**Issue by pabravil** [docarys/docarys#12]
## Description
<a href="URL".>  links are not displayed as markdown links

### Expected behavior

Having <a href="https://github.com/docarys" .>docarys repo</a.> (minus the '.' dots at the end of the tags. A markdown link should be rendered like this when the document is built.

 <a href="https://github.com/docarys" target="_blank">docarys repo</a>

### Actual behavior
Given an HTML <a href="".> link, it is not interpreted, 
<a href="https://github.com/docarys" .>docarys repo</a.>

### Steps to reproduce the bug

Have a document with an HTML <a href="".> link.

**Comment by sesispla** [comment]
Hey @pabravil thank you for your feedback. I am going to have a look on it. Maybe is a configuration of markdown-it (the engine that is running the conversion inside docarys), or maybe is a limitation.

**Comment by sesispla** [comment]
@pabravil I've found that is an option you need to need to enable in markdown-it. Since there is no plugin or per-project markdown-itconfiguration in docarys right not, I've enabled it (plus a html sanitizer plugin). 

See all changes in dd6ea0e.

I am going to release 1.0.7. Please `npm install -g docarys` once released to get the latest version.

**Comment by sesispla** [comment]
Successfully release 1.0.7: https://travis-ci.org/docarys/docarys/builds/281613357
